### ISSUE TITLE
There is no description about Kubernetes monitoring

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1349]
Page: [Subscribing to Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html)

Please add the information about Kubernetes monitoring.

**Comment by netapp-alavoie** [comment]
Thank you for your comment.  What specific sorts of kubernetes monitoring information are you looking to include on this page?

**Comment by kanitani** [comment]
I asked Conahan, Mark <Mark.Conahan@netapp.com> to write the manual more correctly and it has improved a lot. There are still many mistakes in the manual, so I will continue to share information.

**Comment by netapp-alavoie** [comment]
Thank you. Mark and I have worked together and I look forward to his future input.  In the meantime, if there are any updates or corrections you can suggest, feel free to reach out. Since I don't always understand all the technical aspects of a feature, relying on information from those who are more in-the-know is an integral part of successful documentation.

**Comment by netapp-alavoie** [comment]
Closing this ticket.  Please open a new request stating any additional changes needed.
