### ISSUE TITLE
Add Q&A to not run event rate checker on established agents, it may induce latency on monitored SVMs

### ISSUE THREAD

**Issue by omard-netapp** [NetAppDocs/cloudinsights#2176]
Page: [SVM Event Rate Checker (Agent Sizing Guide)](https://docs.netapp.com/us-en/cloudinsights/concept_cs_event_rate_checker.html)

**Comment by netapp-alavoie** [comment]
Thanks for the comment.  Would this statement be accurate in this case?

Q:  What happens if I run the Event Rate Checker with an existing agent? 
A:  Running the Event Rate Checker against an already-existing agent may cause an increase in latency on the SVM. This increase will be temporary in nature while the Event rate Checker is running.

**Comment by netapp-alavoie** [comment]
This Q&A has been added to the Event Rate Checker doc page.   Thank you for the suggestion.
